# Generated by Django 5.2.6 on 2025-10-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_title',
            field=models.CharField(default='Null', max_length=100),
            preserve_default=False,
        ),
    ]
